version: '3.8'

services:
  app:
    image: node:14.15.1-alpine
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start
    networks:
      - crwn-clothing
        
networks:
  crwn-clothing:
    driver: bridge      
